---
name:        "CalVer"
description: "Opinionated CalVer versioning"
branding:
  color: "white"
  icon:  "calendar"
inputs:
  token:
    description: "GitHub token (use {{ github.token }})"
    required:    true
outputs:
  series:
    description: "series"
  version:
    description: "version"

runs:
  using: docker
  image: docker://ghcr.io/mikluko/action-calver:v24.11.7-pr2.44.6060368
  env:
    GH_TOKEN: ${{ inputs.token }}
