---
name:        "CalVer"
description: "Opinionated CalVer versioning"
branding:
  color: "white"
  icon:  "calendar"
inputs:
  modifier:
    description: "Modifier to add to the version"
    required:    false
  token:
    description: "GitHub token (use {{ github.token }})"
    required:    true
outputs:
  version:
    description: "version"

runs:
  using: docker
  image: docker://ghcr.io/mikluko/action-calver:v24.11.4
  args:
    - ${{ inputs.modifier }}
  env:
    GH_TOKEN: ${{ inputs.token }}
