---
name:        "CalVer"
description: "Opinionated CalVer versioning"
branding:
  color: "white"
  icon:  "calendar"
inputs:
  github_token:
    description: "GitHub token to use"
    required:    false
outputs:
  series:
    description: "series"
  version:
    description: "version"

runs:
  using: docker
  image: docker://ghcr.io/mikluko/action-calver:${VERSION}
  env:
    GH_TOKEN: ${{ inputs.token || github.token }}
