on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - action.yaml
      - README.md
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - action.yaml
      - README.md

concurrency:
  group:              ${{ github.workflow }}/${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}

      - name: Generate Calendar Version
        id:   calver
        uses: mikluko/action-calver@v24.11.4
        with:
          token:    ${{ github.token }}
          modifier: pr${{ github.event.pull_request.number }}.${{ github.run_number }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build container
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.calver.outputs.version }}

      - name: Generate files from templates
        run:  for file in templates/*; do envsubst '${VERSION}' < $file > ${file#templates/}; done
        env:
          VERSION: ${{ steps.calver.outputs.version || 'unspecified' }}

      - uses: actions-js/push@master
        with:
          github_token: ${{ github.token }}
          branch:       ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
          message:      "chore: generate files for ${{ steps.calver.outputs.version }} release"

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run:  gh release create "${{ steps.calver.outputs.version }}" --title "${{ steps.calver.outputs.version }}" --generate-notes
