on:
  push:
    branches:
      - main
    paths-ignore:
      - action.yaml
      - README.md

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Calendar Version
        id:   calver
        uses: mikluko/action-calver@v24.11.4
        with:
          token:  ${{ github.token }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build container
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.calver.outputs.next_version }}

      - name: Update version in files
        run:  |
              git config user.name "GitHub Actions [Bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              sed -i "s/v[0-9]\+.[0-9]\+.[0-9]\+/${{ steps.calver.outputs.next_version }}/g" action.yaml
              git add action.yaml 
              sed -i "s/v[0-9]\+.[0-9]\+.[0-9]\+/${{ steps.calver.outputs.next_version }}/g" README.md
              git add README.md
              git commit -m "Release ${{ steps.calver.outputs.next_version }}" --allow-empty
              git push

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run:  gh release create "${{ steps.calver.outputs.next_version }}" --title "${{ steps.calver.outputs.next_version }}" --generate-notes
